services:
  php8:
    container_name: "spatial-php8"
    platform: linux/amd64
    build:
      context: ./php8
    volumes:
      - ${APP_FOLDER}:/var/www
  database-pgsql:
    container_name: "spatial-postgis"
    image: postgis/postgis
    platform: linux/amd64 # Force amd64 for Apple M1/M2 and ARM environments    
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
      PGDATA: /var/lib/postgresql/data-postgis/pgdata
    ports:
      - "5432:5432"
  database-mysql5:
    image: mysql:5.7
    platform: linux/amd64 # Force amd64 for Apple M1/M2 and ARM environments    
    container_name: "spatial-mysql5"
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: main
      MYSQL_PASSWORD: main
      MYSQL_ROOT_PASSWORD: main
      MYSQL_PORT: 3306
    ports:
      - "3357:3306"
  database-mysql8:
    image: mysql:8
    container_name: "spatial-mysql8"
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: main
      MYSQL_PASSWORD: main
      MYSQL_ROOT_PASSWORD: main
      MYSQL_PORT: 3306
    ports:
      - "3380:3306"
  service_doc:
    container_name: "spatial-doc"
    build:
      context: ./sphinx
    volumes:
      - ${APP_FOLDER}/docs:/etc/Sphinx/source
      - ${APP_FOLDER}/docs/build:/etc/Sphinx/build
    ports:
      - 8800:80
  database-mariadb:
    image: mariadb:latest
    container_name: "spatial-mariadb"
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: main
      MYSQL_PASSWORD: main
      MYSQL_ROOT_PASSWORD: main
      MYSQL_PORT: 3306
    ports:
      - "3390:3306"
  database-mssql-2017:
    # Docker Hub image
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: "spatial-mssql-2017"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: mainExtendedToMoreThan8Chars
    ports:
      - 2017:1433
    # Set health checks to wait until mssql-server has started
#        options: >-
#          --health-cmd="/opt/mssql-tools/bin/sqlcmd -S http://localhost:2017 -U sa -P mainExtendedToMoreThan8Chars -Q 'SELECT 1'"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
