name: PHP Tests

on:
  schedule:
    - cron: '0 17 * * 4'
  workflow_dispatch:
  push:
    branches:
      - main
      - 5.0.x-dev
      - 7.x-dev
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '.readthedocs.yaml'
      - 'LICENSE'
  pull_request:
    branches:
      - main
      - 5.0.x-dev
      - 7.x-dev
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '.readthedocs.yaml'
      - 'LICENSE'

permissions:
  contents: read

jobs:
  tests-php:
    name: PHP 8.4 — Tests Without a DBMS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          extensions: mbstring, intl

      - name: Validate composer.json
        run: composer validate --strict

      - name: Create the composer.lock for the cache key
        run: composer update --no-install

      - name: Restore cache Composer dependencies
        uses: actions/cache@v6
        with:
          path: vendor/
          key: ${{ format('{0}-composer-php84-{1}', runner.os, hashFiles('composer.lock')) }}
          restore-keys: ${{ format('{0}-composer-php84-', runner.os) }}

      - name: Install libraries
        run: composer install -vvv

      - name: Copy test suites
        run: cp .github/phpunit.no-database-server.xml .

      - name: Run PHP test group
        run: composer run-script test-php-only

      - name: Cache Composer PHP-CS-Fixer packages
        uses: actions/cache@v6
        with:
          path: quality/php-cs-fixer/vendor/
          key: ${{ format('{0}-phpcsfixer-{1}', runner.os, hashFiles('quality/php-cs-fixer/vendor/composer.lock')) }}
          restore-keys: ${{ format('{0}-phpcsfixer-', runner.os) }}

      - name: Install PHP-CS-Fixer
        run: composer install --working-dir=quality/php-cs-fixer

      - name: Run PHP-CS-Fixer
        run: ./quality/php-cs-fixer/vendor/bin/php-cs-fixer fix --config=quality/php-cs-fixer/.php-cs-fixer.php --dry-run --allow-risky=yes --diff

      - name: Cache Composer PHP-MESS-DETECTOR packages
        uses: actions/cache@v6
        with:
          path: quality/php-mess-detector/vendor/
          key: ${{ format('{0}-phpmd-{1}', runner.os, hashFiles('quality/php-mess-detector/vendor/composer.lock')) }}
          restore-keys: ${{ format('{0}-phpmd-', runner.os) }}

      - name: Install PHP-MESS-DETECTOR
        run: composer install --working-dir=quality/php-mess-detector

      - name: Run PHP-MESS-DETECTOR on lib directory
        run: ./quality/php-mess-detector/vendor/bin/phpmd lib text quality/php-mess-detector/ruleset.xml

      - name: Run PHP-MESS-DETECTOR on tests directory
        run: ./quality/php-mess-detector/vendor/bin/phpmd tests text quality/php-mess-detector/test-ruleset.xml

      - name: Cache Composer PHP-CS packages
        uses: actions/cache@v6
        with:
          path: quality/php-code-sniffer/vendor/
          key: ${{ format('{0}-phpcs-{1}', runner.os, hashFiles('quality/php-code-sniffer/vendor/composer.lock')) }}
          restore-keys: ${{ format('{0}-phpcs-', runner.os) }}

      - name: Install PHP-CS
        run: composer install --working-dir=quality/php-code-sniffer

      - name: Run PHP-CS
        run: ./quality/php-code-sniffer/vendor/bin/phpcs --standard=quality/php-code-sniffer/phpcs.xml -s

      - name: Cache Composer PHP-STAN packages
        uses: actions/cache@v6
        with:
          path: quality/php-stan/vendor/
          key: ${{ format('{0}-phpstan-{1}', runner.os, hashFiles('quality/php-stan/vendor/composer.lock')) }}
          restore-keys: ${{ format('{0}-phpstan-', runner.os) }}

      - name: Install PHP-STAN
        run: composer install --working-dir=quality/php-stan

      - name: Run PHP-STAN
        run: ./quality/php-stan/vendor/bin/phpstan analyse --configuration=quality/php-stan/php-stan.neon lib tests --error-format=table --no-progress --no-interaction --no-ansi --level=9 --memory-limit=256M -v

  tests-minimum-database-versions:
    needs: tests-php
    name: PHP 8.4 — Tests with Minimum DBMS Versions
    runs-on: ubuntu-latest
    env:
      HAS_CC_SECRET: ${{secrets.CODECOV_TOKEN != '' }}
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_DATABASE: main
          MYSQL_USER: main
          MYSQL_PASSWORD: main
          MYSQL_ROOT_PASSWORD: main
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      mariadb:
        image: mariadb:10.11
        env:
          MARIADB_ALLOW_EMPTY_PASSWORD: yes
          MARIADB_DATABASE: main
          MARIADB_USER: main
          MARIADB_PASSWORD: main
          MARIADB_ROOT_PASSWORD: main
        ports:
          - 3310:3306
      postgres:
        image: postgis/postgis:15-3.5
        env:
          POSTGRES_PASSWORD: main
          POSTGRES_USER: main
          POSTGRES_DATABASE: main
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: mainExtendedToMoreThan8Chars
        ports:
          - 1433:1433
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Microsoft ODBC Driver for SQL Server
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          extensions: mbstring, intl, pdo_mysql, pdo_pgsql, pdo_sqlsrv, sqlsrv, xdebug

      - name: Validate composer.json
        run: composer validate --strict

      - name: Create the composer.lock for the cache key
        run: composer update --no-install

      - name: Restore cache Composer dependencies
        uses: actions/cache@v6
        with:
          path: vendor/
          key: ${{ format('{0}-composer-php84-{1}', runner.os, hashFiles('composer.lock')) }}
          restore-keys: ${{ format('{0}-composer-php84-', runner.os) }}

      - name: Install libraries
        run: composer install -vvv

      - name: Copy test suites
        run: cp .github/phpunit.*.xml .

      - name: Run complete test suite
        run: composer run-script test-coverage

      - name: Upload coverage to Codecov
        if: ${{ env.HAS_CC_SECRET == 'true' }}
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: .phpunit.cache/code-coverage/clover.xml
          slug: longitude-one/doctrine-spatial

  tests-maximum-database-versions:
    needs: tests-minimum-database-versions
    name: PHP 8.5 — Tests with Maximum DBMS Versions
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:9.6
        env:
          MYSQL_DATABASE: main
          MYSQL_USER: main
          MYSQL_PASSWORD: main
          MYSQL_ROOT_PASSWORD: main
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      mariadb:
        image: mariadb:12.3
        env:
          MARIADB_ALLOW_EMPTY_PASSWORD: yes
          MARIADB_DATABASE: main
          MARIADB_USER: main
          MARIADB_PASSWORD: main
          MARIADB_ROOT_PASSWORD: main
        ports:
          - 3310:3306
      postgres:
        image: postgis/postgis:18-3.6
        env:
          POSTGRES_PASSWORD: main
          POSTGRES_USER: main
          POSTGRES_DATABASE: main
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mssql:
        image: mcr.microsoft.com/mssql/server:2025-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: mainExtendedToMoreThan8Chars
        ports:
          - 1433:1433
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Microsoft ODBC Driver for SQL Server
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

      - name: Setup PHP 8.5
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          tools: composer:v2
          extensions: mbstring, intl, pdo_mysql, pdo_pgsql, pdo_sqlsrv, sqlsrv

      - name: Validate composer.json
        run: composer validate --strict

      - name: Create the composer.lock for the cache key
        run: composer update --no-install

      - name: Restore cache Composer dependencies
        uses: actions/cache@v6
        with:
          path: vendor/
          key: ${{ format('{0}-composer-php85-{1}', runner.os, hashFiles('composer.lock')) }}
          restore-keys: ${{ format('{0}-composer-php85-', runner.os) }}

      - name: Force doctrine/orm library to 4.0.x-dev
        run: composer --prefer-stable require "doctrine/orm:^4.0" --with-all-dependencies

      - name: Copy test suites
        run: cp .github/phpunit.*.xml .

      - name: Run complete test suite
        run: composer run-script test
