name: Tests with Maximum DBMS Versions

on:
  workflow_run:
    workflows:
      - Tests with Minimum DBMS Versions
    types:
      - completed

permissions:
  contents: read

jobs:
  tests-maximum-database-versions:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: PHP 8.5 - Maximum DBMS Versions
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:9.6
        env:
          MYSQL_DATABASE: main
          MYSQL_USER: main
          MYSQL_PASSWORD: main
          MYSQL_ROOT_PASSWORD: main
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      mariadb:
        image: mariadb:12.3
        env:
          MARIADB_ALLOW_EMPTY_PASSWORD: yes
          MARIADB_DATABASE: main
          MARIADB_USER: main
          MARIADB_PASSWORD: main
          MARIADB_ROOT_PASSWORD: main
        ports:
          - 3310:3306
      postgres:
        image: postgis/postgis:18-3.6
        env:
          POSTGRES_PASSWORD: main
          POSTGRES_USER: main
          POSTGRES_DATABASE: main
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mssql:
        image: mcr.microsoft.com/mssql/server:2025-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: mainExtendedToMoreThan8Chars
        ports:
          - 1433:1433
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install Microsoft ODBC Driver for SQL Server
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

      - name: Setup PHP 8.5
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          tools: composer:v2
          extensions: mbstring, intl, pdo_mysql, pdo_pgsql, pdo_sqlsrv, sqlsrv

      - name: Validate composer.json
        run: composer validate --strict

      - name: Create the composer.lock for the cache key
        run: composer update --no-install

      - name: Restore cache Composer dependencies
        uses: actions/cache@v6
        with:
          path: vendor/
          key: ${{ format('{0}-composer-php85-{1}', runner.os, hashFiles('composer.lock')) }}
          restore-keys: ${{ format('{0}-composer-php85-', runner.os) }}

      - name: Force doctrine/orm library to 4.0.x-dev
        run: composer --prefer-stable require "doctrine/orm:^4.0" --with-all-dependencies

      - name: Copy test suites
        run: cp .github/phpunit.*.xml .

      - name: Run complete test suite
        run: composer run-script test
